  name: review_app
  on:
    pull_request
  
  jobs:
    review_app:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      steps:
        - name: Cloning repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Push to dokku
          uses: dokku/github-action@master
          with:
            command: review-apps:create
            git_remote_url: 'ssh://dokku@dokku.me:22/appname'
            review_app_name: review-appname-${{ github.event.pull_request.number }}
            ssh_private_key: ${{ secrets.KEY }}
  
    destroy_review_app:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      steps:
        - name: Destroy the review app
          uses: dokku/github-action@master
          with:
            command: review-apps:destroy
            git_remote_url: 'ssh://dokku@dokku.me:22/appname'
            review_app_name: review-appname-${{ github.event.pull_request.number }}
            ssh_private_key: ${{ secrets.KEY }}