  name: review_app
  on:
    pull_request
  
  jobs:      
    destroy_review_app:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && (github.event.action == 'closed' || github.event.action == 'synchronize')
      steps:
        - name: Destroy the review app
          uses: dokku/github-action@master
          with:
            command: review-apps:destroy
            git_remote_url: 'ssh://dokku@${{ secrets.HOST }}:22/dokkuapp'
            review_app_name: dokkuapp-${{ github.event.pull_request.number }}
            ssh_private_key: ${{ secrets.KEY }}
            
    create_review_app:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
      steps:
        - name: Cloning repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Push to dokku
          uses: dokku/github-action@master
          with:
            command: review-apps:create
            git_remote_url: 'ssh://dokku@${{ secrets.HOST }}:22/dokkuapp'
            review_app_name: dokkuapp-${{ github.event.pull_request.number }}
            ssh_private_key: ${{ secrets.KEY }}